'use strict';
// universal error handler to handle all errors generated by Axios
const serviceRemover = require('./serviceRemover.js');

module.exports = (error, noConnectionErr, next, serviceName, serviceURL)=>{

  if (!error.response) {
    // fire up moitor
    
    serviceRemover(serviceName, serviceURL);
    console.log('updated global list: ', global.services);
    return next(noConnectionErr);
  } else {
    const receivedError = {'message_spec':error.response.data , 'statusCode': error.response.status, 'statusMessage': error.response.statusText };
    console.log('updated global list: ', global.services);
    return next(receivedError);
    // fire up minitor
  }
};
