'use strict';
// universal error handler to handle all errors generated by Axios
const serviceRemover = require('./serviceRemover.js');

module.exports = (error, noConnectionErr, next, serviceName, serviceURL)=>{

  if (!error.response) {
    serviceRemover(serviceName, serviceURL);
    next(noConnectionErr);
  } else {
    const receivedError = {'message_spec':error.response.data , 'statusCode': error.response.status, 'statusMessage': error.response.statusText };
    next(receivedError);
  }
};
